'use client';

export default function Page() {
  return (
    <div className="mt-16 md:mt-32 mb-24">
      <div className="w-full px-4 pt-10">
        <div className="w-full text-center md-5 md:mb-10 relative">
          <h1 className="text-transparent bg-clip-text bg-gradient-to-b from-[#bdbdbd] text-5xl md:text-6xl font-LDR mb-3">
            TERMS OF USE
          </h1>
          <p className="text-[#bdbdbd] xs:text-xl md:text-lg">Last update is July 1st, 2023</p>
          <div className="w-full h-[1px] bg-gradient-line mt-5"></div>
        </div>
        <div className="md:m-20 text-sm">
          <p className="text-white text-left">
            Terms and Conditions Please read these terms and conditions carefully before using Our Service.
            <br />
            Interpretation and Definitions
            <br />
            Interpretation
            <br />
            <br />
            The words of which the initial letter is capitalized have meanings defined
            <br />
            under the following conditions. The following definitions shall have the same meaning regardless of whether
            <br />
            they appear in singular or in plural. <br />
            Definitions
            <br />
            <br />
            For the purposes of these Terms of Use:
            <br />
            <br />
            “Affiliate” means an entity that controls, is controlled by or is under common control with a party, where
            "control" means ownership of 50% or more of the shares,
            <br />
            equity interest or other securities entitled to vote for election of directors or other managing authority.
            <br />
            “Account” means a unique account created for You to access our Service
            <br />
            or parts of our Service. “Company” (referred to as either "the Company", "We", "Us" or "Our" in this
            Agreement) refers to [COMPANY_INFORMATION].
            <br />
            “Country” refers to [COMPANY_COUNTRY].
            <br />
            “Content” refers to content such as text, images, or other information that can be posted, uploaded, linked
            to or otherwise made available by You, regardless of the form of that content.
            <br />
            “Device” means any device that can access the Service such as a computer, a cell phone or a digital tablet.
            <br />
            “Feedback” means feedback, innovations or suggestions sent by You regarding the attributes, performance or
            features of our Service.
            <br />
            “Service” refers to the Website.
            <br />
            “Terms of Use” (also referred as "Terms") mean these Terms of Use that form the entire agreement between You
            and the Company regarding the use of the Service. This Terms of Use Agreement was generated by TermsFeed
            Terms of Use Generator.
            <br />
            “Third-party Social Media Service” means any services or content (including data, information, products or
            services) provided by a third-party that may be displayed, included or made available by the Service.
            <br />
            “Website” refers to [WEBSITE_NAME], accessible from [WEBSITE_URL]
            <br />
            “You” means the individual accessing or using the Service, or the company, or other legal entity on behalf
            of which such individual is accessing or using the Service, as applicable.
            <br />
            Acknowledgment
            <br />
            <br />
            These are the Terms of Use governing the use of this Service and the agreement that operates between You and
            the Company. These Terms of Use set out the rights and obligations of all users regarding the use of the
            Service.
            <br />
            <br />
            Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms
            of Use. These Terms of Use apply to all visitors, users and others who access or use the Service.
            <br />
            <br />
            By accessing or using the Service You agree to be bound by these Terms of Use. If You disagree with any part
            of these Terms of Use then You may not access the Service.
            <br />
            <br />
            You represent that you are over the age of 18. The Company does not permit those under 18 to use the
            Service.
            <br />
            <br />
            Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the
            Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection,
            use and disclosure of Your personal information when You use the Application or the Website and tells You
            about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before
            using Our Service.
            <br />
            User Accounts
            <br />
            <br />
            When You create an account with Us, You must provide Us information that is accurate, complete, and current
            at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination
            of Your account on Our Service.
            <br />
            <br />
            You are responsible for safeguarding the password that You use to access the Service and for any activities
            or actions under Your password, whether Your password is with Our Service or a Third-Party Social Media
            Service.
            <br />
            <br />
            You agree not to disclose Your password to any third party. You must notify Us immediately upon becoming
            aware of any breach of security or unauthorized use of Your account.
            <br />
            <br />
            You may not use as a username the name of another person or entity or that is not lawfully available for
            use, a name or trademark that is subject to any rights of another person or entity other than You without
            appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.
            <br />
            Content
            <br />
            Your Right to Post Content
            <br />
            <br />
            Our Service allows You to post Content. You are responsible for the Content that You post to the Service,
            including its legality, reliability, and appropriateness.
            <br />
            <br />
            By posting Content to the Service, You grant Us the right and license to use, modify, publicly perform,
            publicly display, reproduce, and distribute such Content on and through the Service.
            <br />
          </p>
        </div>
        <div className="w-full h-[1px] bg-gradient-line mt-5"></div>
      </div>
    </div>
  );
}
